const { Product } = require("../models");

const productData = [
  {
    product_title: "Bulbasaur",
    price: 1.99,
    inventory: 1,
    category_id: 5,
  },
  {
    product_title: "Ivysaur",
    price: 2.99,
    inventory: 2,
    category_id: 5,
  },
  {
    product_title: "Venusaur",
    price: 3.99,
    inventory: 3,
    category_id: 5,
  },
  {
    product_title: "Charmander",
    price: 4.99,
    inventory: 4,
    category_id: 2,
  },
  {
    product_title: "Charmeleon",
    price: 5.99,
    inventory: 5,
    category_id: 2,
  },
  {
    product_title: "Charizard",
    price: 6.99,
    inventory: 6,
    category_id: 2,
  },
  {
    product_title: "Squirtle",
    price: 7.99,
    inventory: 7,
    category_id: 3,
  },
  {
    product_title: "Wartortle",
    price: 8.99,
    inventory: 8,
    category_id: 3,
  },
  {
    product_title: "Blastoise",
    price: 9.99,
    inventory: 9,
    category_id: 3,
  },
  {
    product_title: "Caterpie",
    price: 10.99,
    inventory: 10,
    category_id: 12,
  },
  {
    product_title: "Metapod",
    price: 11.99,
    inventory: 11,
    category_id: 12,
  },
  {
    product_title: "Butterfree",
    price: 12.99,
    inventory: 12,
    category_id: 12,
  },
  {
    product_title: "Weedle",
    price: 13.99,
    inventory: 13,
    category_id: 12,
  },
  {
    product_title: "Kakuna",
    price: 14.99,
    inventory: 14,
    category_id: 12,
  },
  {
    product_title: "Beedrill",
    price: 15.99,
    inventory: 15,
    category_id: 12,
  },
  {
    product_title: "Pidgey",
    price: 16.99,
    inventory: 16,
    category_id: 1,
  },
  {
    product_title: "Pidgeotto",
    price: 17.99,
    inventory: 17,
    category_id: 1,
  },
  {
    product_title: "Pidgeot",
    price: 18.99,
    inventory: 18,
    category_id: 1,
  },
  {
    product_title: "Rattata",
    price: 19.99,
    inventory: 19,
    category_id: 1,
  },
  {
    product_title: "Raticate",
    price: 20.99,
    inventory: 20,
    category_id: 1,
  },
  {
    product_title: "Spearow",
    price: 21.99,
    inventory: 21,
    category_id: 1,
  },
  {
    product_title: "Fearow",
    price: 22.99,
    inventory: 22,
    category_id: 1,
  },
  {
    product_title: "Ekans",
    price: 23.99,
    inventory: 23,
    category_id: 8,
  },
  {
    product_title: "Arbok",
    price: 24.99,
    inventory: 24,
    category_id: 8,
  },
  {
    product_title: "Pikachu",
    price: 25.99,
    inventory: 25,
    category_id: 4,
  },
  {
    product_title: "Raichu",
    price: 26.99,
    inventory: 26,
    category_id: 4,
  },
  {
    product_title: "Sandshrew",
    price: 27.99,
    inventory: 27,
    category_id: 9,
  },
  {
    product_title: "Sandslas",
    price: 28.99,
    inventory: 28,
    category_id: 9,
  },
  {
    product_title: "hNidoran ♀",
    price: 29.99,
    inventory: 29,
    category_id: 9,
  },
  {
    product_title: "Nidorina",
    price: 30.99,
    inventory: 30,
    category_id: 9,
  },
  {
    product_title: "Nidoqueen",
    price: 31.99,
    inventory: 39,
    category_id: 9,
  },
  {
    product_title: "Nidoran ♂",
    price: 32.99,
    inventory: 32,
    category_id: 9,
  },
  {
    product_title: "Nidorino",
    price: 33.99,
    inventory: 33,
    category_id: 9,
  },
  {
    product_title: "Nidoking",
    price: 34.99,
    inventory: 34,
    category_id: 9,
  },
  {
    product_title: "Clefairy",
    price: 35.99,
    inventory: 35,
    category_id: 18,
  },
  {
    product_title: "Clefable",
    price: 36.99,
    inventory: 36,
    category_id: 18,
  },
  {
    product_title: "Vulpix",
    price: 37.99,
    inventory: 37,
    category_id: 2,
  },
  {
    product_title: "Ninetales",
    price: 38.99,
    inventory: 38,
    category_id: 2,
  },
  {
    product_title: "Jigglypuff",
    price: 39.99,
    inventory: 39,
    category_id: 18,
  },
  {
    product_title: "Wigglytuff",
    price: 40.99,
    inventory: 40,
    category_id: 18,
  },
  {
    product_title: "Zubat",
    price: 41.99,
    inventory: 41,
    category_id: 8,
  },
  {
    product_title: "Golbat",
    price: 42.99,
    inventory: 42,
    category_id: 8,
  },
  {
    product_title: "Oddish",
    price: 43.99,
    inventory: 43,
    category_id: 5,
  },
  {
    product_title: "Gloom",
    price: 44.99,
    inventory: 44,
    category_id: 5,
  },
  {
    product_title: "Vileplume",
    price: 45.99,
    inventory: 45,
    category_id: 5,
  },
  {
    product_title: "Paras",
    price: 46.99,
    inventory: 46,
    category_id: 12,
  },
  {
    product_title: "Parasect",
    price: 47.99,
    inventory: 47,
    category_id: 12,
  },
  {
    product_title: "Venonat",
    price: 48.99,
    inventory: 48,
    category_id: 12,
  },
  {
    product_title: "Venomoth",
    price: 49.99,
    inventory: 49,
    category_id: 12,
  },
  {
    product_title: "Diglett",
    price: 50.99,
    inventory: 50,
    category_id: 9,
  },
  {
    product_title: "Dugtrio",
    price: 51.99,
    inventory: 51,
    category_id: 9,
  },
  {
    product_title: "Meowth",
    price: 52.99,
    inventory: 52,
    category_id: 1,
  },
  {
    product_title: "Persian",
    price: 53.99,
    inventory: 53,
    category_id: 1,
  },
  {
    product_title: "Psyduck",
    price: 54.99,
    inventory: 54,
    category_id: 3,
  },
  {
    product_title: "Golduck",
    price: 55.99,
    inventory: 55,
    category_id: 3,
  },
  {
    product_title: "Mankey",
    price: 56.99,
    inventory: 56,
    category_id: 7,
  },
  {
    product_title: "Primeape",
    price: 57.99,
    inventory: 57,
    category_id: 7,
  },
  {
    product_title: "Growlithe",
    price: 58.99,
    inventory: 58,
    category_id: 2,
  },
  {
    product_title: "Arcanine",
    price: 59.99,
    inventory: 59,
    category_id: 2,
  },
  {
    product_title: "Poliwag",
    price: 60.99,
    inventory: 60,
    category_id: 3,
  },
  {
    product_title: "Poliwhirl",
    price: 61.99,
    inventory: 61,
    category_id: 3,
  },
  {
    product_title: "Poliwrath",
    price: 62.99,
    inventory: 62,
    category_id: 3,
  },
  {
    product_title: "Abra",
    price: 63.99,
    inventory: 63,
    category_id: 15,
  },
  {
    product_title: "Kadabra",
    price: 64.99,
    inventory: 64,
    category_id: 15,
  },
  {
    product_title: "Alakazam",
    price: 65.99,
    inventory: 65,
    category_id: 15,
  },
  {
    product_title: "Machop",
    price: 66.99,
    inventory: 66,
    category_id: 1,
  },
  {
    product_title: "Machoke",
    price: 67.99,
    inventory: 67,
    category_id: 7,
  },
  {
    product_title: "Machamp",
    price: 68.99,
    inventory: 68,
    category_id: 7,
  },
  {
    product_title: "Bellsprout",
    price: 69.99,
    inventory: 69,
    category_id: 5,
  },
  {
    product_title: "Weepinbell",
    price: 70.99,
    inventory: 70,
    category_id: 5,
  },
  {
    product_title: "Victreebel",
    price: 71.99,
    inventory: 71,
    category_id: 5,
  },
  {
    product_title: "Tentacool",
    price: 72.99,
    inventory: 72,
    category_id: 3,
  },
  {
    product_title: "Tentacruel",
    price: 73.99,
    inventory: 73,
    category_id: 3,
  },
  {
    product_title: "Geodude",
    price: 74.99,
    inventory: 74,
    category_id: 13,
  },
  {
    product_title: "Graveler",
    price: 75.99,
    inventory: 75,
    category_id: 13,
  },
  {
    product_title: "Golem",
    price: 76.99,
    inventory: 76,
    category_id: 13,
  },
  {
    product_title: "Ponyta",
    price: 77.99,
    inventory: 77,
    category_id: 2,
  },
  {
    product_title: "Rapidash",
    price: 78.99,
    inventory: 78,
    category_id: 2,
  },
  {
    product_title: "Slowpoke",
    price: 79.99,
    inventory: 79,
    category_id: 3,
  },
  {
    product_title: "Slowbro",
    price: 80.99,
    inventory: 80,
    category_id: 3,
  },
  {
    product_title: "Magnemite",
    price: 81.99,
    inventory: 81,
    category_id: 4,
  },
  {
    product_title: "Magneton",
    price: 82.99,
    inventory: 82,
    category_id: 4,
  },
  {
    product_title: "Farfetch-d",
    price: 83.99,
    inventory: 83,
    category_id: 1,
  },
  {
    product_title: "Doduo",
    price: 84.99,
    inventory: 84,
    category_id: 1,
  },
  {
    product_title: "Dodrio",
    price: 85.99,
    inventory: 85,
    category_id: 1,
  },
  {
    product_title: "Seel",
    price: 86.99,
    inventory: 86,
    category_id: 3,
  },
  {
    product_title: "Dewgong",
    price: 87.99,
    inventory: 87,
    category_id: 3,
  },
  {
    product_title: "Grimer",
    price: 88.99,
    inventory: 88,
    category_id: 8,
  },
  {
    product_title: "Muk",
    price: 89.99,
    inventory: 89,
    category_id: 8,
  },
  {
    product_title: "Shellder",
    price: 90.99,
    inventory: 90,
    category_id: 3,
  },
  {
    product_title: "Cloyster",
    price: 91.99,
    inventory: 91,
    category_id: 3,
  },
  {
    product_title: "Gastly",
    price: 92.99,
    inventory: 92,
    category_id: 14,
  },
  {
    product_title: "Haunter",
    price: 93.99,
    inventory: 93,
    category_id: 14,
  },
  {
    product_title: "Gengar",
    price: 94.99,
    inventory: 94,
    category_id: 14,
  },
  {
    product_title: "Onix",
    price: 95.99,
    inventory: 95,
    category_id: 13,
  },
  {
    product_title: "Drowzee",
    price: 96.99,
    inventory: 96,
    category_id: 11,
  },
  {
    product_title: "Hypno",
    price: 97.99,
    inventory: 97,
    category_id: 11,
  },
  {
    product_title: "Krabby",
    price: 98.99,
    inventory: 98,
    category_id: 3,
  },
  {
    product_title: "Kingler",
    price: 99.99,
    inventory: 99,
    category_id: 3,
  },
  {
    product_title: "Voltorb",
    price: 100.99,
    inventory: 100,
    category_id: 4,
  },
  {
    product_title: "Electrode",
    price: 101.99,
    inventory: 101,
    category_id: 4,
  },
  {
    product_title: "Exeggcute",
    price: 102.99,
    inventory: 102,
    category_id: 5,
  },
  {
    product_title: "Exeggutor",
    price: 103.99,
    inventory: 103,
    category_id: 5,
  },
  {
    product_title: "Cubone",
    price: 104.99,
    inventory: 104,
    category_id: 9,
  },
  {
    product_title: "Marowak",
    price: 105.99,
    inventory: 105,
    category_id: 9,
  },
  {
    product_title: "Hitmonlee",
    price: 106.99,
    inventory: 106,
    category_id: 7,
  },
  {
    product_title: "Hitmonchan",
    price: 107.99,
    inventory: 107,
    category_id: 7,
  },
  {
    product_title: "Lickitung",
    price: 108.99,
    inventory: 108,
    category_id: 1,
  },
  {
    product_title: "Koffing",
    price: 109.99,
    inventory: 109,
    category_id: 8,
  },
  {
    product_title: "Weezing",
    price: 110.99,
    inventory: 110,
    category_id: 8,
  },
  {
    product_title: "Rhyhorn",
    price: 111.99,
    inventory: 111,
    category_id: 9,
  },
  {
    product_title: "Rhydon",
    price: 112.99,
    inventory: 112,
    category_id: 9,
  },
  {
    product_title: "Chansey",
    price: 113.99,
    inventory: 113,
    category_id: 1,
  },
  {
    product_title: "Tangela",
    price: 114.99,
    inventory: 114,
    category_id: 5,
  },
  {
    product_title: "Kangaskhan",
    price: 115.99,
    inventory: 115,
    category_id: 1,
  },
  {
    product_title: "Horsea",
    price: 116.99,
    inventory: 116,
    category_id: 3,
  },
  {
    product_title: "Seadra",
    price: 117.99,
    inventory: 117,
    category_id: 3,
  },
  {
    product_title: "Goldeen",
    price: 118.99,
    inventory: 118,
    category_id: 3,
  },
  {
    product_title: "Seaking",
    price: 119.99,
    inventory: 119,
    category_id: 3,
  },
  {
    product_title: "Staryu",
    price: 120.99,
    inventory: 120,
    category_id: 3,
  },
  {
    product_title: "Starmie",
    price: 121.99,
    inventory: 121,
    category_id: 3,
  },
  {
    product_title: "Mr. Mime",
    price: 122.99,
    inventory: 122,
    category_id: 11,
  },
  {
    product_title: "Scyther",
    price: 123.99,
    inventory: 123,
    category_id: 12,
  },
  {
    product_title: "Jynx",
    price: 124.99,
    inventory: 124,
    category_id: 6,
  },
  {
    product_title: "Electabuzz",
    price: 125.99,
    inventory: 125,
    category_id: 4,
  },
  {
    product_title: "Magmar",
    price: 126.99,
    inventory: 126,
    category_id: 2,
  },
  {
    product_title: "Pinsir",
    price: 127.99,
    inventory: 127,
    category_id: 12,
  },
  {
    product_title: "Tauros",
    price: 128.99,
    inventory: 128,
    category_id: 1,
  },
  {
    product_title: "Magikarp",
    price: 129.99,
    inventory: 129,
    category_id: 3,
  },
  {
    product_title: "Gyarados",
    price: 130.99,
    inventory: 130,
    category_id: 3,
  },
  {
    product_title: "Lapras",
    price: 131.99,
    inventory: 131,
    category_id: 3,
  },
  {
    product_title: "Ditto",
    price: 132.99,
    inventory: 132,
    category_id: 1,
  },
  {
    product_title: "Eevee",
    price: 133.99,
    inventory: 133,
    category_id: 1,
  },
  {
    product_title: "Vaporeon",
    price: 134.99,
    inventory: 134,
    category_id: 3,
  },
  {
    product_title: "Jolteon",
    price: 135.99,
    inventory: 135,
    category_id: 4,
  },
  {
    product_title: "Flareon",
    price: 136.99,
    inventory: 136,
    category_id: 2,
  },
  {
    product_title: "Porygon",
    price: 137.99,
    inventory: 137,
    category_id: 1,
  },
  {
    product_title: "Omanyte",
    price: 138.99,
    inventory: 138,
    category_id: 13,
  },
  {
    product_title: "Omastar",
    price: 139.99,
    inventory: 139,
    category_id: 13,
  },
  {
    product_title: "Kabuto",
    price: 140.99,
    inventory: 140,
    category_id: 13,
  },
  {
    product_title: "Kabutops",
    price: 141.99,
    inventory: 141,
    category_id: 13,
  },
  {
    product_title: "Aerodactyl",
    price: 142.99,
    inventory: 142,
    category_id: 13,
  },
  {
    product_title: "Snorlax",
    price: 143.99,
    inventory: 143,
    category_id: 1,
  },
  {
    product_title: "Articuno",
    price: 144.99,
    inventory: 144,
    category_id: 6,
  },
  {
    product_title: "Zapdos",
    price: 145.99,
    inventory: 145,
    category_id: 4,
  },
  {
    product_title: "Moltres",
    price: 146.99,
    inventory: 146,
    category_id: 2,
  },
  {
    product_title: "Dratini",
    price: 147.99,
    inventory: 147,
    category_id: 15,
  },
  {
    product_title: "Dragonair",
    price: 148.99,
    inventory: 148,
    category_id: 15,
  },
  {
    product_title: "Dragonite",
    price: 149.99,
    inventory: 149,
    category_id: 15,
  },
  {
    product_title: "Mewtwo",
    price: 150.99,
    inventory: 150,
    category_id: 11,
  },
  {
    product_title: "Mewtwo",
    price: 151.99,
    inventory: 151,
    category_id: 11,
  },
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
